#!/usr/bin/env bash

DF_FILENAME="$2"
DF_TYPE="$3"

# Check arguments
function usage() {
    echo " $(basename $0) [u,upload|d,download|f,full|a,add <filename> <static|templates|synced>]"
    exit
}
function upload() {

    # Enter dotfiles dir
    cd "$DOTFILES_SOURCE_DIR"

    # Make git up to date
    git pull origin;

    # Sync changes of synced files

    # Enter synced folder
    cd synced;

    # Copy files
    rsync --exclude ".git/" \
		-rptgoE --ignore-non-existing ~/ .;

    cd ..;

    # Review changes
    echo -e "\nChanges synced from home directory, please review git status:\n"
    git status;
    read -p "Continue (yes/no)? " -n 1 -r
    echo    # (optional) move to a new line
    if [[ ! $REPLY =~ ^[Yy]$ ]]
    then
        exit 1
    fi

    # Commit and push
    git add .
    git commit -m "Automated sync"
    git push origin

}
function download() {
    
    # Enter dotfiles dir
    cd "$DOTFILES_SOURCE_DIR"

    # Make git up to date
    git pull origin;

   # Enter static folder
	cd static;

	# Copy files
	rsync --exclude ".git/" \
		-rptgoE . ~;

    cd ..

    # Enter template folder
	cd static;

	# Copy files
	rsync --exclude ".git/" \
		-rptgoE --ignore-existing . ~;

    cd ..
    
    #Enter synced folder
    cd synced;

    # Copy files
    rsync --exclude ".git/" \
		--update -rptgoE . ~;

    cd ..;

	
}
function full() {
    download
    upload
}
function add() {
  if [ -z "$DF_FILENAME" ]; then
      echo "Filename missing"
      usage;
  fi
  if ! [[ -f "$DF_FILENAME" ]]; then
      echo "File does not exist"
      usage;
  fi
  if [ -z "$DF_TYPE" ]; then
      echo "Type missing"
      usage;
  fi
  if ! [[ -d "$DOTFILES_SOURCE_DIR/$DF_TYPE" ]]; then
    echo "Invalid dotfile type '$DF_TYPE'"
    usage;
  fi
  echo -e "\nAdding file $DF_FILENAME as $DF_TYPE dotfile"
  cp $DF_FILENAME "$DOTFILES_SOURCE_DIR/$DF_TYPE/"
  git add "$DOTFILES_SOURCE_DIR/$DF_TYPE/"
  echo -e "\nUploading to git...\n"
  upload
  echo -e "\nDone\n"
}
if [ -z $1 ]; then
    usage;
fi
if [ -z "$DOTFILES_SOURCE_DIR" ]; then
   echo -e "environent variable DOTFILES_SOURCE_DIR not set, have you forgot to log in/out after bootstrapping?"
   echo -e "Aborting..."
   exit
fi;
 case $1 in

  u|upload)
    upload
    ;;

  d|download)
    download
    ;;

  f|full)
    full
    ;;

  a|add)
    add
    ;;
  *)
    usage
    ;;
esac
